### ISSUE TITLE
BUG on integers

### ISSUE THREAD

**Issue by sorosj** [dxma/perl5-json-jq#11]
When an integer, which is longer than 32 bit, is read from a JSON file, it will be truncated to 32 bit.

**Comment by dxma** [comment]
Thanks for reporting, @retcheverry has provided a PR to fix this. It is now merged.
Please give a try and come back to us in case of error.

Cheers,

**Comment by cmaile** [comment]
@dxma can you update the code on metacpan?

**Comment by dxma** [comment]
sure, I will cut a new release.
