### ISSUE TITLE
Tests failing on perls compiled with -Duselongdouble

### ISSUE THREAD

**Issue by andk** [dxma/perl5-json-jq#13]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/4678fcb6-001c-11ed-b4f4-42d70cb46c39

Comparing floating point numbers requires a bit of tolerance, maybe a case to try out Test::Number::Delta.

**Comment by dxma** [comment]
Thank you for letting me know. I think I've fixed it in latest release.
