### ISSUE TITLE
[QUESTION] Is there any replacement for the jq binary command-line options?

### ISSUE THREAD

**Issue by XSven** [dxma/perl5-json-jq#16]
You can affect how the jq binary reads and writes its input and output using command-line options. Let's assume I have started to work with the jq binary using its command-line options and I want to switch to JSON::JQ. How do I deal with the command-line options?

**Comment by dxma** [comment]
hi,

As you highlighted, the jq binary command-line options mostly fall into categories below:

1. input preprocess.
2. output postprocess.
3. jq control.
4. terminal control / formatting.

For 1 and 2, it is perfectly covered by perl itself. What you can pass as input is ordinary perl hash or array. It means you can use whatever modules / means available in perl to preprocess or make it. Perl is very good at text and formatting things. Similar concept holds for output postprocess, you can do what you plan once retrieving output data from the function call.
It is the true power of making it as a binding, it is not dealing with string only on input/output.

For 3 it is covered in some way, I made some option support.
For 4 it can be made easily as well in perl, check modules with 'term' or 'tk' keywords.
