### ISSUE TITLE
Memory errors

### ISSUE THREAD

**Issue by benkasminbullock** [dxma/perl5-json-jq#3]
At the moment on FreeBSD the module is crashing with segmentation fault errors.

Here: 

https://github.com/dxma/perl5-json-jq/blob/25fc67143e9ba1a69ff92f63119c06942f301377/lib/JSON/JQ.xs#L316

it is freeing result, but then later it is using result:

https://github.com/dxma/perl5-json-jq/blob/25fc67143e9ba1a69ff92f63119c06942f301377/lib/JSON/JQ.xs#L347

and again it frees result:

https://github.com/dxma/perl5-json-jq/blob/25fc67143e9ba1a69ff92f63119c06942f301377/lib/JSON/JQ.xs#L362

I ran this under [valgrind](https://www.valgrind.org/) and there were lots of errors about memory:

https://gist.github.com/benkasminbullock/f02980d4033224f01e1af16a34024168

**Comment by dxma** [comment]
Yeah I developed this binding on Windows with strawberry perl, it works there.
Yesterday I noticed the same segfault on Linux. Trying to understand what is wrong.

**Comment by benkasminbullock** [comment]
Valgrind catches most of these things. Two other easy things which help with memory problems in C are setting the variable to 0 after freeing:

     free (result);
     result = 0;

and counting mallocs and frees:

     x = malloc (100);
     n_mallocs++;
     y = malloc (300);
     n_mallocs--;

     free (x);
     n_mallocs--;

then at the end of the program:

     if (n_mallocs != 0) {
          fprintf (stderr, "n_mallocs = %d\n", n_mallocs);
     }

There are lots of other things you can do such as using memory sanitizer etc. but these easy methods actually get a lot of the problems.

**Comment by benkasminbullock** [comment]
I tried version 0.03 from CPAN and it installed OK so I'll close this.
