### ISSUE TITLE
Halts with "Wide character in subroutine entry"

### ISSUE THREAD

**Issue by benkasminbullock** [dxma/perl5-json-jq#7]
Using the synopsis example
````
use JSON::JQ;
my $jq = JSON::JQ->new({ script => '.' });
my $results = $jq->process({ json_file => 'foo.json' });
# check items in @$results
print "@$results\n";
````
on the following JSON file:
````
{
	"U+835C":{
		"orig":"⿱艹毕"
	}
}
````
it dies with an error
````
$ perl json-jq.pl
Wide character in subroutine entry at /home/ben/software/install/lib/perl5/site_perl/5.32.1/JSON.pm line 190.
`````
It looks like you need to do some encoding checks.

**Comment by dxma** [comment]
Would you mind sharing me the input json file ?
It is supposed to be taken care of by JSON::from_json and Path::Tiny::slurp_utf8, where I set utf8 flag on.

**Comment by benkasminbullock** [comment]
The input file is this:

https://gist.github.com/benkasminbullock/9a4ab965910fe0fd5a523832c45fe509

It is part of a JSON conversion of a very big text file from here:

https://github.com/cjkvi/cjkvi-ids/blob/master/ids.txt

**Comment by dxma** [comment]
I found the issue and prepared a fix in my local branch.
There is another core dump problem which I got on my work machine, I am trying to reproduce it again.
Once ready I will cut a new release with fix for this encoding problem.
thanks.
